# First Attempt

In [1]:
import pandas as pd
import seaborn as sb 
import numpy as np

In [2]:
data = pd.read_csv("kidney_disease_complete_2b.csv")

In [3]:
data.head()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48,80,1.020,1,0,normal,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,2,62,80,1.010,2,3,normal,normal,notpresent,notpresent,...,31,7500,3.7,no,yes,no,poor,no,yes,ckd
2,3,48,70,1.005,4,0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
3,4,51,80,1.010,2,0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd
4,5,60,90,1.015,3,0,normal,normal,notpresent,notpresent,...,39,7800,4.4,yes,yes,no,good,yes,no,ckd

In [4]:
data.columns

Index(['id', 'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr',
       'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='object')

In [5]:
data.select_dtypes(include='object')

,rbc,pc,pcc,ba,htn,dm,cad,appet,pe,ane,classification
0,normal,normal,notpresent,notpresent,yes,yes,no,good,no,no,ckd
1,normal,normal,notpresent,notpresent,no,yes,no,poor,no,yes,ckd
2,normal,abnormal,present,notpresent,yes,no,no,poor,yes,yes,ckd
3,normal,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
4,normal,normal,notpresent,notpresent,yes,yes,no,good,yes,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...
375,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
376,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
377,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
378,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
379,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd

In [7]:

import tensorflow as tf

In [8]:
def model():
    ''' Creates a model '''
    print(5)